site_name: Karan's Programming Notes
site_description: Short nuggets of information, code snippets or articles that I want to keep handy.
copyright: Made with ❤️ by Karan.
repo_name: mr-karan/notes
repo_url: https://github.com/mr-karan/notes
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  shortcuts:
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - navigation.instant
    - tabs
  font:
    text: Inter
    code: IMB Plex Mono

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mr-karan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrkaran_
nav:
  - Home: index.md
  - CLI:
      - cli/get-local-ip.md
      - cli/pritunl-systemd-resolved-issues.md
      - cli/most-used-commands.md
      - cli/curl.md
  - K8s:
      - k8s/resource-utilisation.md
      - k8s/kubectl-cheatsheet.md
  - Docker:
      - docker/use-custom-dns.md
      - docker/commands.md
  - Postgres:
      - postgres/wal-log-reset.md
  - Go:
      - go/update-go.md
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
