site_name: Karan's Programming Notes
site_description: Short nuggets of information, code snippets or articles that I want to keep handy.
copyright: Made with ❤️ by Karan.
repo_name: mr-karan/notes
repo_url: https://github.com/mr-karan/notes
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: deep purple
  language: en
  include_search_page: true
  search_index_only: true

plugins:
  - search:
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mr-karan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrkaran_
nav:
  - Home: index.md
  - Snippets:
      - Misc:
          - snippets/misc/utc-local-time.md
          - snippets/misc/screenshot-effects.md
      - K8s:
          - snippets/k8s/resource-utilisation.md
          - snippets/k8s/kubectl-cheatsheet.md
      - Docker:
          - snippets/docker/use-custom-dns.md
          - snippets/docker/commands.md
      - Postgres:
          - snippets/postgres/wal-log-reset.md
      - Go:
          - snippets/go/update-go.md
      - Linux:
          - snippets/linux/get-local-ip.md
          - snippets/linux/pritunl-systemd-resolved-issues.md
          - snippets/linux/most-used-commands.md
          - snippets/linux/curl.md
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
