site_name: Karan's Programming Notes
site_description: Short nuggets of information, code snippets or articles that I want to keep handy.
copyright: Made with ❤️ by Karan.
repo_name: mr-karan/notes
repo_url: https://github.com/mr-karan/notes
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: brown
  language: en
  include_search_page: true
  search_index_only: true

plugins:
  - search:
      prebuild_index: python
      lang:
      - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mr-karan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrkaran_
nav:
- Home: index.md
- Snippets:
  - snippets/misc/utc-local-time.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
